using System.Text;
using TkHLSL.Ir;
using TkHLSL.Model;
using TkHLSL.Text;

namespace TkHLSL.SourceGeneration.Emit;

/// <summary>
///     Renders a successfully-parsed <see cref="HlslCompilationResult" /> into the generated C# partial
///     type: <c>Properties</c> (cached <c>Shader.PropertyToID</c> ids), a constructor, one nested
///     kernel type per <see cref="Ir.EntryPoint" /> with per-resource setters and
///     <c>DispatchThreads</c>/<c>DispatchGroups</c>, outer-level setters for plain globals and
///     <c>cbuffer</c> members, and one element <c>struct</c> per user <c>struct</c> used as a
///     <c>StructuredBuffer&lt;T&gt;</c>-family element type — see docs/IMPLEMENTATION_PLAN.md §9 Phase 9.4.
/// </summary>
/// <remarks>
///     A pure function of its inputs (no I/O, no Roslyn symbols) so it can run inside the incremental
///     pipeline's cached <c>Select</c> step and be unit-tested directly without a Compilation.
/// </remarks>
internal static class CodeEmitter
{
    /// <summary>Carries what <see cref="MakeDiagnostic" /> needs to turn an HLSL <see cref="TextSpan" /> into a file + line/column, without threading three separate parameters through every Emit* method.</summary>
    private readonly struct EmitContext
    {
        public EmitContext(SourceText source, IReadOnlyDictionary<string, string> filesByPath, string rootPath)
        {
            Source = source;
            FilesByPath = filesByPath;
            RootPath = rootPath;
        }

        public SourceText Source { get; }
        public IReadOnlyDictionary<string, string> FilesByPath { get; }
        public string RootPath { get; }
    }

    public static (string Source, List<EmitDiagnosticInfo> Diagnostics) Emit(AttributeTargetInfo target,
        HlslCompilationResult result, IReadOnlyDictionary<string, string> filesByPath, string rootPath)
    {
        var diagnostics = new List<EmitDiagnosticInfo>();
        var context = new EmitContext(result.Source, filesByPath, rootPath);
        var sb = new StringBuilder();

        sb.Append("// <auto-generated/>\n");
        sb.Append("// Generated by TkHLSL.SourceGeneration from '").Append(target.Path).Append("'.\n");
        sb.Append("#nullable enable\n\n");

        var hasNamespace = target.Namespace.Length > 0;
        var indent = "";
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(target.Namespace)
                .Append('\n').Append("{\n");
            indent = "    ";
        }

        for (var i = 0; i < target.TypeChain.Count; i++)
        {
            var entry = target.TypeChain[i];
            sb.Append(indent).Append("partial ").Append(entry.Keyword).Append(' ').Append(entry.Name)
                .Append('\n').Append(indent).Append("{\n");
            indent += "    ";
        }

        EmitBody(sb, indent, target, result, context, diagnostics);

        for (var i = target.TypeChain.Count - 1; i >= 0; i--)
        {
            indent = indent.Substring(0, indent.Length - 4);
            sb.Append(indent).Append("}\n");
        }

        if (hasNamespace) sb.Append("}\n");

        return (sb.ToString(), diagnostics);
    }

    private static void EmitBody(StringBuilder sb, string indent, AttributeTargetInfo target,
        HlslCompilationResult result, EmitContext context, List<EmitDiagnosticInfo> diagnostics)
    {
        var typeName = target.TypeChain[target.TypeChain.Count - 1].Name;

        // --- Properties (Shader.PropertyToID cache) ------------------------------------------------
        sb.Append(indent).Append("public static class Properties\n").Append(indent).Append("{\n");
        foreach (var name in DistinctPropertyNames(result))
            sb.Append(indent).Append("    public static readonly int ").Append(name)
                .Append(" = global::UnityEngine.Shader.PropertyToID(\"").Append(EscapeString(name)).Append("\");\n");
        sb.Append(indent).Append("}\n\n");

        // --- Constructor + kernel properties ---------------------------------------------------------
        sb.Append(indent).Append("public global::UnityEngine.ComputeShader Shader { get; }\n\n");

        foreach (var kernel in result.Kernels)
            sb.Append(indent).Append("public ").Append(KernelTypeName(kernel.Name)).Append(' ')
                .Append(KernelPropertyName(kernel.Name)).Append(" { get; }\n");
        if (result.Kernels.Count > 0) sb.Append('\n');

        sb.Append(indent).Append("public ").Append(typeName)
            .Append("(global::UnityEngine.ComputeShader shader)\n").Append(indent).Append("{\n");
        sb.Append(indent)
            .Append("    Shader = shader ?? throw new System.ArgumentNullException(nameof(shader));\n");
        foreach (var kernel in result.Kernels)
            sb.Append(indent).Append("    ").Append(KernelPropertyName(kernel.Name)).Append(" = new ")
                .Append(KernelTypeName(kernel.Name)).Append("(shader);\n");
        sb.Append(indent).Append("}\n\n");

        // --- Outer-level setters: plain globals + cbuffer members ------------------------------------
        foreach (var resource in result.AllResources)
            switch (resource.ResourceKind)
            {
                case ResourceKind.PlainGlobal:
                    EmitUniformSetter(sb, indent, resource.Name, resource.ElementTypeName, resource.Location,
                        context, diagnostics);
                    break;
                case ResourceKind.CBuffer or ResourceKind.ConstantBuffer:
                    EmitConstantBufferSetter(sb, indent, resource);
                    foreach (var field in resource.Fields)
                        EmitUniformSetter(sb, indent, field.Name, field.TypeName, field.Location, context,
                            diagnostics, field.ArrayLength);
                    break;
                case ResourceKind.SamplerState or ResourceKind.SamplerComparisonState:
                    sb.Append(indent).Append("// '").Append(resource.Name)
                        .Append("': Unity の ComputeShader API にサンプラーを直接設定する手段がないため生成をスキップしました。\n");
                    break;
            }

        sb.Append('\n');

        // --- Kernel structs ----------------------------------------------------------------------------
        foreach (var kernel in result.Kernels)
            EmitKernel(sb, indent, kernel, context, diagnostics);

        // --- StructuredBuffer<T>-family element structs -----------------------------------------------
        foreach (var s in DistinctElementStructs(result))
            EmitElementStruct(sb, indent, s, context, diagnostics);
    }

    private static void EmitKernel(StringBuilder sb, string indent, KernelBindingInfo kernel, EmitContext context,
        List<EmitDiagnosticInfo> diagnostics)
    {
        var kernelType = KernelTypeName(kernel.Name);
        sb.Append(indent).Append("public readonly struct ").Append(kernelType).Append('\n')
            .Append(indent).Append("{\n");
        var i = indent + "    ";

        sb.Append(i).Append("public const int NumThreadsX = ").Append(kernel.ThreadGroupSize.X).Append(";\n");
        sb.Append(i).Append("public const int NumThreadsY = ").Append(kernel.ThreadGroupSize.Y).Append(";\n");
        sb.Append(i).Append("public const int NumThreadsZ = ").Append(kernel.ThreadGroupSize.Z).Append(";\n\n");

        sb.Append(i).Append("private readonly global::UnityEngine.ComputeShader _shader;\n");
        sb.Append(i).Append("public readonly int Index;\n\n");

        sb.Append(i).Append("internal ").Append(kernelType)
            .Append("(global::UnityEngine.ComputeShader shader)\n").Append(i).Append("{\n");
        sb.Append(i).Append("    _shader = shader;\n");
        sb.Append(i).Append("    Index = shader.FindKernel(\"").Append(EscapeString(kernel.Name)).Append("\");\n");
        sb.Append(i).Append("}\n\n");

        foreach (var binding in kernel.Bindings) EmitKernelResourceSetter(sb, i, binding, context, diagnostics);

        sb.Append(i).Append("public void DispatchGroups(int groupsX, int groupsY, int groupsZ)\n");
        sb.Append(i).Append("    => _shader.Dispatch(Index, groupsX, groupsY, groupsZ);\n\n");

        sb.Append(i)
            .Append(
                "/// <summary>Divides by numthreads (rounding up) and dispatches — pass the number of elements to process, not the group count.</summary>\n");
        sb.Append(i).Append("public void DispatchThreads(int threadsX, int threadsY, int threadsZ)\n");
        sb.Append(i).Append("    => _shader.Dispatch(Index,\n");
        sb.Append(i).Append("        (threadsX + NumThreadsX - 1) / NumThreadsX,\n");
        sb.Append(i).Append("        (threadsY + NumThreadsY - 1) / NumThreadsY,\n");
        sb.Append(i).Append("        (threadsZ + NumThreadsZ - 1) / NumThreadsZ);\n");

        sb.Append(indent).Append("}\n\n");
    }

    private static void EmitKernelResourceSetter(StringBuilder sb, string indent, ResourceBinding binding,
        EmitContext context, List<EmitDiagnosticInfo> diagnostics)
    {
        var setterName = SetterName(binding.Name);
        var propertyName = PropertyName(binding.Name);

        switch (binding.ResourceKind)
        {
            case ResourceKind.Texture2D or ResourceKind.Texture2DArray or ResourceKind.Texture3D
                or ResourceKind.TextureCube or ResourceKind.TextureCubeArray:
                sb.Append(indent).Append("public void ").Append(setterName)
                    .Append("(global::UnityEngine.Texture value)\n");
                sb.Append(indent).Append("    => _shader.SetTexture(Index, Properties.").Append(propertyName)
                    .Append(", value);\n\n");
                break;

            case ResourceKind.RWTexture2D or ResourceKind.RWTexture2DArray or ResourceKind.RWTexture3D:
                sb.Append(indent).Append("public void ").Append(setterName)
                    .Append("(global::UnityEngine.RenderTexture value)\n");
                sb.Append(indent).Append("    => _shader.SetTexture(Index, Properties.").Append(propertyName)
                    .Append(", value);\n\n");
                break;

            case ResourceKind.StructuredBuffer or ResourceKind.RWStructuredBuffer
                or ResourceKind.AppendStructuredBuffer or ResourceKind.ConsumeStructuredBuffer
                or ResourceKind.ByteAddressBuffer or ResourceKind.RWByteAddressBuffer:
                sb.Append(indent).Append("public void ").Append(setterName)
                    .Append("(global::UnityEngine.ComputeBuffer value)\n");
                sb.Append(indent).Append("    => _shader.SetBuffer(Index, Properties.").Append(propertyName)
                    .Append(", value);\n\n");
                sb.Append(indent).Append("public void ").Append(setterName)
                    .Append("(global::UnityEngine.GraphicsBuffer value)\n");
                sb.Append(indent).Append("    => _shader.SetBuffer(Index, Properties.").Append(propertyName)
                    .Append(", value);\n\n");
                break;

            case ResourceKind.SamplerState or ResourceKind.SamplerComparisonState:
            case ResourceKind.PlainGlobal:
            case ResourceKind.CBuffer or ResourceKind.ConstantBuffer:
                // A kernel's GlobalUses includes every global it references, not just resource
                // types — a plain uniform or cbuffer member the kernel body reads still shows up
                // here. Those already got a setter at the outer level in EmitBody; nothing to
                // emit per-kernel for them.
                break;

            default:
                diagnostics.Add(MakeDiagnostic("TKH1005", context, binding.Location,
                    binding.Name, binding.ResourceKind.ToString()));
                break;
        }
    }

    private static void EmitUniformSetter(StringBuilder sb, string indent, string name, string? hlslType,
        TextSpan location, EmitContext context, List<EmitDiagnosticInfo> diagnostics, int? arrayLength = null)
    {
        if (hlslType is null || !HlslTypeMap.TryMapUniform(hlslType, out var mapping))
        {
            diagnostics.Add(MakeDiagnostic("TKH1005", context, location, name, hlslType ?? "?"));
            return;
        }

        var setterName = SetterName(name);
        var propertyName = PropertyName(name);

        if (arrayLength is null)
        {
            sb.Append(indent).Append("public void ").Append(setterName).Append('(').Append(mapping.CSharpType)
                .Append(" value)\n");
            sb.Append(indent).Append("    => Shader.").Append(mapping.SetterMethod).Append("(Properties.")
                .Append(propertyName).Append(", value);\n\n");
        }
        else
        {
            sb.Append(indent).Append("public void ").Append(setterName).Append('(').Append(mapping.CSharpType)
                .Append("[] values)\n");
            sb.Append(indent).Append("    => Shader.").Append(mapping.SetterMethod).Append("Array(Properties.")
                .Append(propertyName).Append(", values);\n\n");
        }
    }

    private static void EmitConstantBufferSetter(StringBuilder sb, string indent, ResourceBinding cbuffer)
    {
        var setterName = SetterName(cbuffer.Name);
        var propertyName = PropertyName(cbuffer.Name);
        sb.Append(indent).Append("public void ").Append(setterName)
            .Append("(global::UnityEngine.ComputeBuffer value, int offset, int size)\n");
        sb.Append(indent).Append("    => Shader.SetConstantBuffer(Properties.").Append(propertyName)
            .Append(", value, offset, size);\n\n");
    }

    private static void EmitElementStruct(StringBuilder sb, string indent, HlslStruct s, EmitContext context,
        List<EmitDiagnosticInfo> diagnostics)
    {
        sb.Append(indent)
            .Append(
                "[System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]\n");
        sb.Append(indent).Append("public struct ").Append(SanitizeIdentifier(s.Name)).Append('\n')
            .Append(indent).Append("{\n");

        // Note: unlike a cbuffer member, a StructuredBuffer<T> element is *not* subject to HLSL's
        // 16-byte constant-buffer packing rule — it is packed tightly, the same as a C#
        // [StructLayout(Sequential)] struct — so there is no packing check to run here.
        foreach (var field in s.Fields)
        {
            if (!HlslTypeMap.TryMapField(field.TypeName, out var mapping))
            {
                diagnostics.Add(MakeDiagnostic("TKH1005", context, field.Location, field.Name, field.TypeName));
                continue;
            }

            var csharpType = field.ArrayLength is not null ? mapping.CSharpType + "[]" : mapping.CSharpType;
            sb.Append(indent).Append("    public ").Append(csharpType).Append(' ')
                .Append(SanitizeIdentifier(field.Name));
            if (field.ArrayLength is { } arrayLength)
                sb.Append(" /* [").Append(arrayLength)
                    .Append("] — HLSL pads each array element to 16 bytes; size this array accordingly */");
            sb.Append(";\n");
        }

        sb.Append('\n');
        sb.Append(indent).Append("    public static int Stride => System.Runtime.InteropServices.Marshal.SizeOf<")
            .Append(SanitizeIdentifier(s.Name)).Append(">();\n");
        sb.Append(indent).Append("}\n\n");
    }

    // --- naming ------------------------------------------------------------------------------------

    private static string KernelTypeName(string kernelName)
    {
        return SanitizeIdentifier(kernelName) + "Kernel";
    }

    private static string KernelPropertyName(string kernelName)
    {
        return SanitizeIdentifier(kernelName);
    }

    /// <summary>The generated <c>Set_&lt;name&gt;</c> member name for an HLSL identifier, kept verbatim (see docs/IMPLEMENTATION_PLAN.md §9 decisions: "HLSL name used as-is").</summary>
    private static string SetterName(string hlslName)
    {
        return "Set" + PropertySeparator(hlslName) + SanitizeIdentifier(hlslName);
    }

    private static string PropertyName(string hlslName)
    {
        return SanitizeIdentifier(hlslName);
    }

    private static string PropertySeparator(string hlslName)
    {
        return hlslName.Length > 0 && hlslName[0] == '_' ? "" : "_";
    }

    /// <summary>Guards against an HLSL identifier that collides with a C# keyword or starts with a digit.</summary>
    private static string SanitizeIdentifier(string name)
    {
        if (name.Length == 0) return "_";
        return char.IsDigit(name[0]) ? "_" + name : name;
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static IEnumerable<string> DistinctPropertyNames(HlslCompilationResult result)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var resource in result.AllResources)
        {
            if (resource.ResourceKind is ResourceKind.SamplerState or ResourceKind.SamplerComparisonState) continue;

            if (resource.ResourceKind is ResourceKind.CBuffer or ResourceKind.ConstantBuffer)
            {
                if (seen.Add(resource.Name)) yield return PropertyName(resource.Name);
                foreach (var field in resource.Fields)
                    if (seen.Add(field.Name))
                        yield return PropertyName(field.Name);
                continue;
            }

            if (seen.Add(resource.Name)) yield return PropertyName(resource.Name);
        }
    }

    private static IEnumerable<HlslStruct> DistinctElementStructs(HlslCompilationResult result)
    {
        var wanted = new HashSet<string>(StringComparer.Ordinal);
        foreach (var resource in result.AllResources)
            if (resource.ResourceKind is ResourceKind.StructuredBuffer or ResourceKind.RWStructuredBuffer
                    or ResourceKind.AppendStructuredBuffer or ResourceKind.ConsumeStructuredBuffer
                && resource.ElementTypeName is { } elementType)
                wanted.Add(elementType);

        var emitted = new HashSet<string>(StringComparer.Ordinal);
        foreach (var s in result.Structs)
            if (wanted.Contains(s.Name) && emitted.Add(s.Name))
                yield return s;
    }

    /// <summary>
    ///     Resolves <paramref name="span" /> (a composite offset into <see cref="EmitContext.Source" />)
    ///     back to its originating file and converts it to a line/column via <see cref="LineMap" />, so
    ///     the reported <see cref="Microsoft.CodeAnalysis.Location" /> points at the actual
    ///     <c>.compute</c>/<c>.cginc</c> line the resource or struct member was declared on.
    /// </summary>
    private static EmitDiagnosticInfo MakeDiagnostic(string id, EmitContext context, TextSpan span,
        params string[] args)
    {
        if (context.Source.TryGetLocation(span.Start, out var segment, out var offsetInFile))
        {
            var path = segment.Path.Length == 0 ? context.RootPath : segment.Path;
            var text = context.FilesByPath.TryGetValue(path, out var t) ? t : string.Empty;
            return new EmitDiagnosticInfo(id, new EquatableArray<string>(args), path,
                LineMap.GetLinePositionSpan(text, offsetInFile, span.Length));
        }

        return new EmitDiagnosticInfo(id, new EquatableArray<string>(args), context.RootPath,
            new LinePositionSpanInfo(0, 0, 0, 0));
    }
}
