#pragma kernel CSMain

struct Unused
{
    float3 position : POSITION;
    float2 uv;
};

cbuffer Params : register(b0)
{
    float4x4 _WorldToObject;
    float _Radius;
    int _SampleCount;
    float3 _LightDir[4];
    row_major float4x4 _ViewProj;
};

RWStructuredBuffer<float> _Out : register(u0);

[numthreads(1,1,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    _Out[id.x] = _Radius * _SampleCount + _LightDir[0].x + _WorldToObject[0][0] + _ViewProj[0][0];
}
